name: Notify Common

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger submodule update on Common
        run: |
          gh workflow run update-submodules.yml --repo Zappy-Epitech/Common
        env:
          GH_TOKEN: ${{ secrets.COMMON_TOKEN }}
